name: Deploy Laravel

# Trigger the workflow on push and 
# pull request events on the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
# Authenticate to the the server via ssh 
# and run our deployment script 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "cd /var/www/html && ./.scripts/deploy.sh"