name: Test SSH Connection

on:
  workflow_dispatch  # Manually trigger the workflow from GitHub Actions

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "echo 'SSH connection successful!'"
          